### ISSUE TITLE
Database Migration

### ISSUE THREAD

**Issue by thesimplekid** [cashubtc/cdk#119]
Currently there is no established way to migrate the mint nor wallet database when there is a change to the schema. Before v0.1.0 there should be a plan for this as deleting the database and recreating it will result in lost nuts

**Comment by davidcaseria** [comment]
Do you have any initial ideas on how we should handle this?

**Comment by thesimplekid** [comment]
Its actually something that may not be pre v0.1 and will be the the first time we need to change the DB after v0.1. 
Currently only the Key value db is implemented so there isn't a strict schema to migrate. However, we will have to be away of changing structs could cause deserialization to fail.  I've put a version number check in the DB::new function where we can put migration functions as they are needed. However, because of the nature of key value databases we will need to ensure that we create a new version and upgrade path if a struct is changed in a way that will break deserialization, or if a db table is removed or changed. 

SQL database will follow a more structured migration as needed. 

What maybe should be the pre v0.1 task is review the scheme to see if it should be changed to try and reduce needing a major migration though a migration of some sort is inevitable. 

https://github.com/cashubtc/cdk/blob/711175739fe093bdc32bc876170bc395a6cd7829/crates/cdk-redb/src/wallet.rs#L49-L56

**Comment by thesimplekid** [comment]
SQL migrations now can be created the sqlx-cli by calling `sqlx migrate add` and then adding the needed `sql` to the generated file. This can then be called with both the mint and wallet by using. e.g. 
https://github.com/cashubtc/cdk/blob/b474569f3c31b0c6ebd315dd9109211e2c0c6ef7/crates/cdk-cli/src/main.rs#L74-L86
