### ISSUE TITLE
NUT-17: Websockets

### ISSUE THREAD

**Issue by thesimplekid** [cashubtc/cdk#203]
https://github.com/cashubtc/nuts/pull/98#discussion_r1655550190

**Comment by thesimplekid** [comment]
Hey @crodas,

Sure go for it thank you

**Comment by thesimplekid** [comment]
@crodas Have you started on this how is it coming?

**Comment by thesimplekid** [comment]
Yes thats fine. Feel free to publish a draft pr if you want me to take a look at anything even before its working.

**Comment by thesimplekid** [comment]
@crodas I'm going to take this back.

**Comment by prusnak** [comment]
PR https://github.com/cashubtc/cdk/pull/394 has been merged

Should this issue be closed or is there still something left to be done?

**Comment by thesimplekid** [comment]
> Should this issue be closed or is there still something left to be done?

#394 Is mint only so we do still need wallets support, @crodas said he would work on that so lets close this and ill open another tracking issue for that. 

Thanks tracking this.
