### ISSUE TITLE
Release Notes or Changelog Addition

### ISSUE THREAD

**Issue by rodant** [cashubtc/cdk#238]
Hi, concerning possible improvements, I saw a new version 0.2.0 was released and I wanted to quickly check the changes. It would be great to have something like release notes.

**Comment by thesimplekid** [comment]
I did include a [CHANGELOG](https://github.com/cashubtc/cdk/blob/main/CHANGELOG.md), however I'll now also tag them as releases and include the changes as notes there https://github.com/cashubtc/cdk/releases/tag/v0.2.0. To make it clear.  Ill do my best to keep these as complete and accurate as possible.

**Comment by rodant** [comment]
Thanks for the prompt fix! The release description is very helpful.
