### ISSUE TITLE
Refactor(mint): Bring this function into cdk mint or axum

### ISSUE THREAD

**Issue by thesimplekid** [cashubtc/cdk#265]
https://github.com/cashubtc/cdk/blob/5b4aafeb9da1cc3b3254c0f9832039bdd4c0891c/crates/cdk-mintd/src/main.rs#L366-L384

**Comment by prusnak** [comment]
Should this still be open when https://github.com/cashubtc/cdk/commit/90adb3f481f452eebfe1d53c85e9e1e138855cc3 (cherry-picked form https://github.com/cashubtc/cdk/pull/288) has been merged into main?

**Comment by thesimplekid** [comment]
Closed thank you
