### ISSUE TITLE
Support LNbits as LN backend

### ISSUE THREAD

**Issue by prusnak** [cashubtc/cdk#303]
The following crate can be used as LNbits client: https://crates.io/crates/lnbits_rust

**Comment by thesimplekid** [comment]
Looks like this doesn't have the subscribe to incoming invoice that we would uses and hasn't been updated in a bit so I'll likely fork this and add whats needed. Similar to the crates I have for [strike](https://github.com/thesimplekid/strike-rs) and [phoenixd](https://github.com/thesimplekid/phoenixd-rs).

**Comment by prusnak** [comment]
Moksha code for reference: https://github.com/ngutech21/moksha/blob/master/moksha-mint/src/lightning/lnbits.rs
