### ISSUE TITLE
Should update state in database after checking with mint

### ISSUE THREAD

**Issue by thesimplekid** [cashubtc/cdk#353]
https://github.com/cashubtc/cdk/blob/88b79eb9e9620dc9ff9f803ec7702afae4ae0c1b/crates/cdk/src/wallet/mod.rs#L413-L429

**Comment by mubarak23** [comment]
@thesimplekid
can you give more context

 if this is open please assign i will submit a PR for it

**Comment by thesimplekid** [comment]
Right now this only returns the proof state of the checked proofs, we should also update the state in the database.

**Comment by mubarak23** [comment]
> Right now this only returns the proof state of the checked proofs, we should also update the state in the database.

from NUT-04

state is an enum string field with possible values "UNPAID", "PAID", "ISSUED", 

I Assume there field in the mint table where we can update the state 

@thesimplekid

**Comment by thesimplekid** [comment]
https://github.com/cashubtc/cdk/blob/260f262c395056ae243ccc8cfa0e9de793c5fd20/crates/cdk/src/cdk_database/mod.rs#L131-L137

There is an update proof function on the db trait. Spent proofs should be removed, Others shouldn't be changed, as if a proof is `RESERVED` we don't want to change that to `UNSPENT` even though to the mint it is

> state is an enum string field with possible values "UNPAID", "PAID", "ISSUED",

These are the quote states not proof state is here https://github.com/cashubtc/cdk/blob/260f262c395056ae243ccc8cfa0e9de793c5fd20/crates/cdk/src/nuts/nut07.rs#L21-L37

**Comment by mubarak23** [comment]
> update_proofs

so this mean wherever this function is called 

`check_proofs_spent`

we should call this function to update the state

           ```
     self.localstore
                    .update_proofs(unspent_proofs, vec![])
                    .await?;
```

@thesimplekid

**Comment by mubarak23** [comment]
> https://github.com/cashubtc/cdk/blob/260f262c395056ae243ccc8cfa0e9de793c5fd20/crates/cdk/src/cdk_database/mod.rs#L131-L137
> 
> There is an update proof function on the db trait. Spent proofs should be removed, Others shouldn't be changed, as if a proof is `RESERVED` we don't want to change that to `UNSPENT` even though to the mint it is
> 
> > state is an enum string field with possible values "UNPAID", "PAID", "ISSUED",
> 
> These are the quote states not proof. Proog state is here
> 
> https://github.com/cashubtc/cdk/blob/260f262c395056ae243ccc8cfa0e9de793c5fd20/crates/cdk/src/nuts/nut07.rs#L21-L37

@thesimplekid 
so this mean wherever this function is called 

`check_proofs_spent`

we should call this function to update the state

    ```
     self.localstore
                    .update_proofs(unspent_proofs, vec![])
                    .await?;
```

**Comment by thesimplekid** [comment]
We can iterate over the list of `ProofState` `spendable` and use a `.filter_map` to get a list of all the pubkeys that are spent. Those can then be removed from the db using 

```
 self.localstore
                .update_proofs(vec![], spent_proofs)
                .await?;
```

**Comment by mubarak23** [comment]
where the function is called the state is update as seen here, 

[update state](https://github.com/cashubtc/cdk/blob/main/crates/cdk/src/wallet/mod.rs#L339)

execpt there are other place that am missing  @thesimplekid

**Comment by thesimplekid** [comment]
Thats adding the new proofs to the db after the restore. We want to remove `Spent` proof from the database after checking the state. The function can be called externally.

**Comment by mubarak23** [comment]
> Thats adding the new proofs to the db after the restore. We want to remove `Spent` proof from the database after checking the state. The function can be called externally.

am abit lost here,

can you breakdown how you think this issue should be handle @thesimplekid

**Comment by mubarak23** [comment]
i will push a draft PR of what i understand that need to done on the PR

then we can pick it up from there
