### ISSUE TITLE
Add development doc

### ISSUE THREAD

**Issue by thesimplekid** [cashubtc/cdk#396]
Include how to set up dev env, how to run tests (just)

**Comment by mubarak23** [comment]
@thesimplekid i notice some of the Test function require MINT URL to be hard coded

I. [https://github.com/cashubtc/cdk/blob/main/crates/cdk-integration-tests/tests/fake_wallet.rs#L15](https://github.com/cashubtc/cdk/blob/main/crates/cdk-integration-tests/tests/fake_wallet.rs#L15)
