### ISSUE TITLE
Rename pay in cli to melt

### ISSUE THREAD

**Issue by thesimplekid** [cashubtc/cdk#415]

**Comment by mubarak23** [comment]
Can you add description to this, let me work on it

**Comment by mubarak23** [comment]
if i understand the CLI crate correctly, you want to change the [Pay command](https://github.com/cashubtc/cdk/blob/main/crates/cdk-cli/src/main.rs#L54) to Melt command @thesimplekid

**Comment by thesimplekid** [comment]
Yes

**Comment by mubarak23** [comment]
Sending a PR on that regard
