### ISSUE TITLE
Wallet: add support for multiple active keysets per unit

### ISSUE THREAD

**Issue by ok300** [cashubtc/cdk#422]
The wallet has a method `get_active_mint_keyset` which returns:

https://github.com/cashubtc/cdk/blob/09b5a55239787aa623ec6b210a7296fd8b4d8a05/crates/cdk/src/wallet/keysets.rs#L89

This assumes
- the mint has only one active keyset for this unit, or
- all of this mint's active keysets for this unit are equivalent (have the same amounts)

Neither are supported by the spec: https://cashubtc.github.io/nuts/02/#active-keysets

ISTM the wallet should track all active keysets per unit.

**Comment by mubarak23** [comment]
@ok300 so essentially this should return all the keysets, not just the first one as specified above.

**Comment by mubarak23** [comment]
@thesimplekid do we want to return all active keysets since a mint can have at least one  or more active keyset.

**Comment by thesimplekid** [comment]
> @thesimplekid do we want to return all active keysets since a mint can have at least one or more active keyset.l

This would break other parts of cdk that expect this to return the one keyset that it should use in the method. I think what would be best would be to move this logic to a new fn `get_active_mint_keysets` that returns all the active keysets, just this funnction but remove `.first()` and returns a `Vec<KeySetInfo>`.

Then we can change this function `get_active_mint_keyset` to call that function and then select the keyset that should be used, the one with the lowest fee. This way the api is not changed in other parts of the code but we account for the possiblity of multiple active keysets in a more intelligent way.

**Comment by mubarak23** [comment]
> > @thesimplekid do we want to return all active keysets since a mint can have at least one or more active keyset.l
> 
> This would break other parts of cdk that expect this to return the one keyset that it should use in the method. I think what would be best would be to move this logic to a new fn `get_active_mint_keysets` that returns all the active keysets, just this funnction but remove `.first()` and returns a `Vec<KeySetInfo>`.
> 
> Then we can change this function `get_active_mint_keyset` to call that function and then select the keyset that should be used, the one with the lowest fee. This way the api is not changed in other parts of the code but we account for the possiblity of multiple active keysets in a more intelligent way.

understood, 

the lowest fee will be check again `input_fee_ppk` in `KeySetInfo` struct

**Comment by lollerfirst** [comment]
Is there in principle any reason not to have only one active keyset per unit? I know it's not in the specs, but why is my question.

**Comment by thesimplekid** [comment]
> Is there in principle any reason not to have only one active keyset per unit? I know it's not in the specs, but why is my question.

I don't think so, on the mint side cdk will only have one per unit, but thats an implementation choice but since its not defined in the spec for the wallet we have to support multiple.
