### ISSUE TITLE
rename `get_melt_bolt11_quote`

### ISSUE THREAD

**Issue by tdelabro** [cashubtc/cdk#424]
From crates/cdk-axum/src/lib.rs
```rust
        .route("/melt/quote/bolt11", post(get_melt_bolt11_quote))
```

isn't it weird that a POST route calls a method named `get_<...>`? It's at least confusing.

Couldn't it be created `post_melt_bolt11_quote` or `create_melt_bolt11_quote`

**Comment by mubarak23** [comment]
yaah, maybe the function name should change, but `create_melt_bolt11_quote` can be abit off the curve, since the function return `MeltQuoteBolt11Response` and accept ` melt_request: &MeltQuoteBolt11Request`

**Comment by thesimplekid** [comment]
Yeah a rename to `post_...` would make more sense.

**Comment by mubarak23** [comment]
> Yeah a rename to `post_...` would make more sense.

I will send PR for this
