### ISSUE TITLE
Mintd fake wallet: get payment delay from config

### ISSUE THREAD

**Issue by thesimplekid** [cashubtc/cdk#443]
We should allow the payment delay in fake wallet to be configurable. It maybe better to be a range, min and max and choose a random delay between those to to more closely simulate real payments.

https://github.com/cashubtc/cdk/blob/0523892b4db55cedaca59e7e14cc955251357fae/crates/cdk-mintd/src/setup.rs#L224

**Comment by mubarak23** [comment]
I can take and work on this

**Comment by mubarak23** [comment]
> @thesimplekid the setup should collect min and max value, then we choose a random median average value from them.

instead of this. we can generate two random unique value, and get their average

**Comment by thesimplekid** [comment]
> instead of this. we can generate two random unique value, and get their average

I think we still want it in the config, For some testing we may want this to be configurable.
