### ISSUE TITLE
Only store MintKeySetInfo in the DB

### ISSUE THREAD

**Issue by davidcaseria** [cashubtc/cdk#99]
KeySetInfo plus the seed is enough to regenerate the  MintKeySet on start up

https://github.com/cashubtc/cdk/blob/c8e61b34b8014946114823c435b8a086e559efb6/crates/cdk/src/mint.rs#L746

**Comment by thesimplekid** [comment]
closed by [a5a50f2](https://github.com/cashubtc/cdk/commit/a5a50f281c8ad0bb429da1eebe137a11f9086d1d)
